// ── Product Data ──────────────────────────────────────────────────────────────
export const PRODUCTS = [
  {
    id: 1,
    name: "Linen Throw Blanket",
    cat: "home",
    price: 89,
    oldPrice: null,
    rating: 4.8,
    reviews: 142,
    emoji: "🛋️",
    badge: "new",
  },
  {
    id: 2,
    name: "Ceramic Pour-Over Set",
    cat: "kitchen",
    price: 64,
    oldPrice: 79,
    rating: 4.9,
    reviews: 87,
    emoji: "☕",
    badge: "sale",
  },
  {
    id: 3,
    name: "Beeswax Candle Trio",
    cat: "lifestyle",
    price: 38,
    oldPrice: null,
    rating: 4.7,
    reviews: 203,
    emoji: "🕯️",
    badge: "",
  },
  {
    id: 4,
    name: "Herb Garden Starter Kit",
    cat: "garden",
    price: 42,
    oldPrice: null,
    rating: 4.6,
    reviews: 59,
    emoji: "🌿",
    badge: "new",
  },
  {
    id: 5,
    name: "Walnut Cutting Board",
    cat: "kitchen",
    price: 75,
    oldPrice: null,
    rating: 4.9,
    reviews: 311,
    emoji: "🪵",
    badge: "",
  },
  {
    id: 6,
    name: "Merino Wool Scarf",
    cat: "lifestyle",
    price: 98,
    oldPrice: null,
    rating: 4.8,
    reviews: 76,
    emoji: "🧣",
    badge: "",
  },
  {
    id: 7,
    name: "Stoneware Mug Set",
    cat: "kitchen",
    price: 52,
    oldPrice: null,
    rating: 4.7,
    reviews: 128,
    emoji: "🍵",
    badge: "new",
  },
  {
    id: 8,
    name: "Wicker Storage Basket",
    cat: "home",
    price: 47,
    oldPrice: 59,
    rating: 4.5,
    reviews: 94,
    emoji: "🧺",
    badge: "sale",
  },
  {
    id: 9,
    name: "Pressed Flower Frame",
    cat: "home",
    price: 34,
    oldPrice: null,
    rating: 4.6,
    reviews: 67,
    emoji: "🖼️",
    badge: "",
  },
  {
    id: 10,
    name: "Seed Packet Collection",
    cat: "garden",
    price: 28,
    oldPrice: null,
    rating: 4.8,
    reviews: 189,
    emoji: "🌸",
    badge: "new",
  },
  {
    id: 11,
    name: "Natural Soap Bundle",
    cat: "lifestyle",
    price: 45,
    oldPrice: null,
    rating: 4.9,
    reviews: 243,
    emoji: "🧼",
    badge: "",
  },
  {
    id: 12,
    name: "Copper Watering Can",
    cat: "garden",
    price: 68,
    oldPrice: null,
    rating: 4.7,
    reviews: 53,
    emoji: "🪴",
    badge: "",
  },
];

// ── Color Palette ────────────────────────────────────────────────────────────
export const colors = {
  bg: "#f6faf5",
  bg2: "#eef6ec",
  bg3: "#dff1db",
  border: "#d2e3d1",
  border2: "#c5d7c5",
  text: "#2f3f33",
  text2: "#5b6e5f",
  text3: "#8ba08f",
  accent: "#3f8a63",
  accent2: "#74b587",
  accent3: "#cfe4d1",
  mint: "#7dc9b0",
  mint2: "#a8dece",
  mint3: "#d4f0e8",
  lavender: "#a7c4b3",
  lavender2: "#c5d7ca",
  lavender3: "#e3eee7",
  rose: "#d9868b",
  rose2: "#eab3bd",
  rose3: "#f6dcdf",
  butter3: "#f7fbef",
};

// ── Category Styles ──────────────────────────────────────────────────────────
export const catCardBg = {
  home: colors.lavender3,
  kitchen: colors.mint3,
  lifestyle: colors.rose3,
  garden: colors.mint3,
};

export const catChipActive = {
  all: { background: colors.accent, color: "#fff", border: colors.accent },
  home: {
    background: colors.lavender2,
    color: "#5a3a9a",
    border: colors.lavender,
  },
  kitchen: { background: colors.mint2, color: "#1a6a55", border: colors.mint },
  lifestyle: {
    background: colors.rose2,
    color: "#882050",
    border: colors.rose,
  },
  garden: { background: colors.mint2, color: "#1a6a55", border: colors.mint },
};
